---
booktitle: Proceedings of the 1st ContinualAI Unconference, 2023
shortname: CLAI Unconf
volume: '249'
year: '2023'
start: &1 2023-10-09
end: 2023-10-09
published: 2024-08-19
conference_number: '1'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CLAI-Unconf-2023
month: 0
cycles: false
bibtex_editor: Swaroop, Siddharth and Mundt, Martin and Aljundi, Rahaf and Khan, Mohammad
  Emtiyaz
editor:
- given: Siddharth
  family: Swaroop
- given: Martin
  family: Mundt
- given: Rahaf
  family: Aljundi
- given: Mohammad Emtiyaz
  family: Khan
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st ContinualAI Unconference, 2023
    Held in Virtual on 09 October 2023

  Published as Volume 249 by the Proceedings of Machine Learning Research on 19 August 2024.

  Volume Edited by:
    Siddharth Swaroop
    Martin Mundt
    Rahaf Aljundi
    Mohammad Emtiyaz Khan

  Series Editors:
    Neil D. Lawrence
date_str: '09 Oct'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v249"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v249
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v249
email: ''
conference:
  name: ContinualAI Unconference
  url: https://unconf.continualai.org/
  location: Virtual
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v249/clai_unconf23.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v249/clai_unconf23.bib
